
export default new Map([
["src/content/docs/blog/ai-fraud-detection.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fai-fraud-detection.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/ai-replace-content-creator.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fai-replace-content-creator.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/ai-rumor-penalties.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fai-rumor-penalties.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/ai-speed-human-touch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fai-speed-human-touch.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/ai-translation-landing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fai-translation-landing.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/china-us-tariff-turnaround.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fchina-us-tariff-turnaround.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/domestic-ai-breakthrough-2026.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fdomestic-ai-breakthrough-2026.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/doubao-pricing-analysis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Fdoubao-pricing-analysis.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/rare-earth-leak-compliance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Frare-earth-leak-compliance.mdx&astroContentModuleFlag=true")],
["src/content/docs/blog/token-cost-efficiency.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fblog%2Ftoken-cost-efficiency.mdx&astroContentModuleFlag=true")],
["src/content/docs/cases/ecommerce-brand-content-automation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcases%2Fecommerce-brand-content-automation.mdx&astroContentModuleFlag=true")],
["src/content/docs/cases/law-firm-knowledge-base.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcases%2Flaw-firm-knowledge-base.mdx&astroContentModuleFlag=true")],
["src/content/docs/cases/tech-media-localization.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcases%2Ftech-media-localization.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/ai-content-studio.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2Fai-content-studio.mdx&astroContentModuleFlag=true")],
["src/content/docs/products/industry-intelligence.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fproducts%2Findustry-intelligence.mdx&astroContentModuleFlag=true")],
["src/content/docs/solutions/omni-localizer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fsolutions%2Fomni-localizer.mdx&astroContentModuleFlag=true")],
["src/content/docs/solutions/omni-pre-processor.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fsolutions%2Fomni-pre-processor.mdx&astroContentModuleFlag=true")]]);
		